# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true    

    Respinar\ContaoWhatsappBundle\:
        resource: ../src/
        exclude: ../src/ContaoManager

